# Generated by Django 2.0.13 on 2019-05-18 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190518_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpassword',
            field=models.CharField(error_messages={'unique': 'パスワードが規則に従っていません'}, help_text='aaa', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='cpassword'),
        ),
    ]
