# Generated by Django 2.0.13 on 2019-06-03 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190603_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='添付ファイル'),
        ),
    ]
