# Generated by Django 2.0.13 on 2019-05-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft_flg',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
