# Generated by Django 2.0.13 on 2019-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
